version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  eventservices:
    build:
      context: .
      dockerfile: Dockerfile.eventservices
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
